[tool.poetry]
name = "solid"
version = "0.1.0"
description = ""
authors = ["mkrzeminski <mkrzeminski@imgw.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
